DROP TABLE IF EXISTS hospital;
CREATE TABLE IF NOT EXISTS hospital (    
    ID	SERIAL PRIMARY KEY,
    HUALIEN	VARCHAR(5) NOT NULL,
    HOSPITAL	VARCHAR(30) NOT NULL unique,
    TELEPHONE	VARCHAR(15) ,
    ST	VARCHAR(7) ,
    PERSON	VARCHAR(7) ,
    HOME	VARCHAR(50) 
);